# Generated by Django 4.2.7 on 2023-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
